config/routes.rb
Rails.application.routes.draw do

  resources :imports
  get '/imports/doimport/*ipath' => 'imports#doimport', as: 'ipath'
  
  resources :infohash_members
  root to: "mainpage#index"
  
  scope format: true, defaults: { format: 'html' } do
     devise_for :users, controllers: {registrations: "registrations", passwords: "passwords"}
  end
  
  namespace :api do
    namespace :v1 do
      resources :publications
      resources :gfiles
    end
  end

  resources :infohash_members
  resources :identifications  
  
  resources :supervisions
  
  resources :evaluations do
      resources :qualis_evaluate_journasl
  end
  resources :weblinks
  resources :grants

  resources :institutions

  
  get '/u/:username' => 'profiles#username', as: 'username' #creates username_path
  
  resources :profiles do
    resources :positions do
      resources :activities
    end
  end
  
  get '/g/:groupname' => 'groups#groupname', as: 'groupname' #creates groupname_path
    
  resources :groups do
      resources :group_users
  end
  
  get '/h/:code' => 'infohashes#code'
  
  resources :reminders
  resources :posts
  resources :instances
  resources :tags
  resources :gfiles

  resources :folders do
      resources :folder_infohashes
  end
  
  resources :projects do
    resources :project_profiles
  end

  get '/userpublications/:uname' => 'publications#indexbyuser', as: 'uname'
  get '/grouppublications/:gname' => 'publications#indexbygroup', as: 'gname'
  get '/f/:fcode' => 'gfiles#getfile', as: 'fcode'
  
  resources :publications do
    resources :publication_profiles
  end
  
  resources :infohashes do
    resources :infohash_users
    resources :attachments
  end
  
  
  resources :visibilities

  

end

app/models/gfile.rb
class Gfile < ActiveRecord::Base
  HTYPE = 2
  
  belongs_to :infohash   , autosave: true
  
  delegate :user         , to: :infohash
  delegate :members      , to: :infohash
  has_many :infohash_users  , through: :infohash
  
  delegate :gtitle       , to: :infohash
  delegate :gdescription , to: :infohash
  delegate :visibility   , to: :infohash
  delegate :visibility_id, to: :infohash
  
  validates_associated  :infohash      , message: "Failed to validate general information"

  validates_presence_of :filename
  
  has_attached_file :filename #, styles: { medium: "600x400>", thumb: "150x100>" }, default_url: "/images/:style/missing.png"
  #validates_attachment_content_type :filename, content_type: /\Aimage\/.*\Z/
  #validates_attachment_content_type :filename, content_type: ['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'application/zip']
  #validates :filename, attachment_presence: true, validate_media_type: false
  
  do_not_validate_attachment_file_type :filename
  # ALSO DISABLED SPOOF CHECK IN config/initializers/paperclip.rb
  # STILL NEEDING A WORKAROUND FOR FIREFOX AND PDF FILES :(
  
  #validates_attachment_content_type :filename, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/force-download", "application/xls", "application/xlsx", "application/doc", "application/docx", "application/ppt", "application/pptx"]
  
  validates_with AttachmentSizeValidator, attributes: :filename, less_than: 20.megabytes
  
end

app/controllers/api/v1/gfiles_controller.rb
# app/controllers/api/v1/posts_controller.rb
module Api::V1
  class GfilesController < ApiController
    before_action :set_gfile, only: [:show]

    require 'active_support/all'
    #respond_to :json
    
    def index
        respond_with Gfile.all
    end

    def show

    #end
    output = @gfile.infohash.as_json.merge(@gfile.as_json)
    output["url"] = @gfile.filename.url
    output["myrese"] = "v1.0"
    #render json: @publication.as_json(only: [:id, :title, :year, :code])
    render json: output #json.extract! json.myrese "v1.0", @publication #@publication.as_json(only: [:title, :year], include: [:authors, {infohash: {only:[:code]}}] )
    
    end

    private

    def set_gfile
      @gfile = Gfile.find(params[:id])
    end
  end
end

app/controllers/gfiles_controller.rb
class GfilesController < ApplicationController
  before_action :set_gfile, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, :only => [:getfile, :show]
  
  #ssl_required :edit, :update, :destroy, :create
  #ssl_allowed :show, :getfile

  # GET /gfiles
  # GET /gfiles.json
  def index
    #@gfiles = Gfile.all
    @gfiles  = Gfile.joins(:infohash_users).joins(:infohash).where("infohash_users.user_id = ?", current_user.id)
    @gfiles += Gfile.joins(:infohash).where("infohashes.user_id = ?", current_user.id)
    @gfiles.uniq!
  end

  # GET /gfiles/1
  # GET /gfiles/1.json
  def show
  end
  
  def getfile
    infoid = Infohash.where(:code => params['fcode'], :htype => Gfile::HTYPE).first
    fileid = infoid.gfile
    redirect_to fileid.filename.url
  end

  # GET /gfiles/new
  def new
    @gfile = Gfile.new
    @infohash    = Infohash.new
    @gfile.infohash = @infohash
  end

  # GET /gfiles/1/edit
  def edit
    @infohash = @gfile.infohash
  end

  # POST /gfiles
  # POST /gfiles.json
  def create
    #@publication = Publication.new(publication_params)
    @infohash  = Infohash.new(infohash_params)
    @gfile     = @infohash.build_gfile(gfile_params)
    logger.info(gfile_params)
    
    #@mainauthor = params.require(:publication).permit(:mainauthor)

    @infohash.user = current_user
    @infohash.htype_id = Gfile::HTYPE    # GFILE
    @infohash.code     = "file" + Gfile.count.to_s

   respond_to do |format|
      if current_user.profile.quota_usage+(@gfile.filename_file_size/(1024*1024)) > current_user.profile.quota
        flash[:error] = "User quota is exceeded! "+current_user.profile.quota_usage.to_s+" MB > "+current_user.profile.quota.to_s+" MB"
        format.html { render :new }
        format.json { render json: @gfile.errors, status: :unprocessable_entity }
      elsif @gfile.save
        format.html { redirect_to @gfile, notice: 'File was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        #flash[:error] = "PROBLEMAS! BUG NO FIREFOX??"
        format.json { render json: @gfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gfiles/1
  # PATCH/PUT /gfiles/1.json
  def update
    respond_to do |format|
      @gfile.infohash.assign_attributes(infohash_params)
      if @gfile.update(gfile_params)
        format.html { redirect_to @gfile, notice: 'File was successfully updated.' }
        format.json { render :show, status: :ok, location: @gfile }
      else
        format.html { render :edit }
        format.json { render json: @gfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gfiles/1
  # DELETE /gfiles/1.json
  def destroy
    @gfile.infohash.destroy
    respond_to do |format|
      format.html { redirect_to gfiles_url, notice: 'File was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gfile
      @gfile = Gfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gfile_params
      params.require(:gfile).permit(:filename)
    end
    
    def infohash_params
      params.require(:gfile).permit(:gtitle, :gdescription, :visibility_id)
    end
end

app/helpers/gfiles_helper.rb
module GfilesHelper
end

app/views/gfiles/_form.html.erb
<%= form_for(@gfile) do |f| %>

  <h2>General information</h2>
  <% if @infohash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@infohash.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @infohash.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :visibility%><br />
    <%= f.select :visibility_id, options_for_select(Visibility.all.map{|p|[p.vtype, p.id]}, @infohash.visibility_id) %>
  </div>
  
  <div class="field">
    <%= f.label "General title" %><br>
    <%= f.text_field(:gtitle) %>
  </div>

  <div class="field">
    <%= f.label "General description (allows #hashtags, @user-refs, @group-refs and :resource-refs)" %><br>
    <%= f.text_area :gdescription %>
  </div>

  <h2>File information</h2>


  <% if @gfile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gfile.errors.count, "error") %> prohibited this gfile from being saved:</h2>

      <ul>
      <% @gfile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>(*) Mandatory fields</p>

  <div class="field">
    <%= f.label "File (*)" %><br>
    <%= f.file_field :filename, class: "form-control" %>
  </div>
  
  <div class="actions">
    <% if @gfile.persisted? %>
      <%= f.submit "Update File" %>
    <% else %>
      <%= f.submit "Create File" %>  
    <% end %>
  </div>
<% end %>

app/views/gfiles/edit.html.erb
<h1>Editing File</h1>

<%= render 'form' %>

<%= link_to 'Show', @gfile %> |
<%= link_to 'Back', gfiles_path %>

app/views/gfiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Files</h1>

<table>
  <thead>
    <tr>
      <th style="min-width:100px">Name</th>
      <th style="min-width:200px">Description</th>
      <th style="min-width:100px">Members</th>
      <th style="min-width:100px">Tags</th>
      <th>Visibility</th>
      <th style="min-width:100px">Get file</th>
      <th style="min-width:100px">Size</th>
      <th style="min-width:200px">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @gfiles.each do |gfile| %>
      <tr>
        <td><%= gfile.gtitle %></td>
        <td><%= gfile.gdescription %></td>
        <td>
          <b><%= gfile.infohash.user.username %> (owner)</b> <br>
          <% gfile.infohash.infohash_users.each do |u| %> 
            <%= u.user.username %>
            <% if current_user == gfile.user%>
              <%= link_to "(delete)", [gfile.infohash, u] ,method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            <br>
          <% end %>
          <% if current_user == gfile.user #owner %>
              <%= link_to "New member", new_infohash_infohash_user_path(gfile.infohash) %>
          <% end %>
        </td>
        <td>
          <% gfile.infohash.tags.each do |t| %> 
            <%= t.tagname %>
          <% end %>
        </td>
        <td><%= gfile.visibility.vtype %></td>
        <td><%= link_to "Download", gfile.filename.url %></td>
        <td>
          <% if gfile.filename_file_size/(1024.0*1024.0) < 1 %>
            <%= (gfile.filename_file_size/1024.0).round(2) %> KB
          <% else %>
            <%= (gfile.filename_file_size/(1024.0*1024.0)).round(2) %> MB
          <% end %>
        </td>
        
        <td>
          <div class="btn-group" role="group" aria-label="...">
            <%= link_to 'Show', gfile, class: 'btn btn-default' %>
            <% if current_user == gfile.user %>
              <%= link_to 'Edit', edit_gfile_path(gfile), class: 'btn' %>
              <%= link_to 'Destroy', gfile, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>
            <% end %>
          </div>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File', new_gfile_path %>

app/views/gfiles/new.html.erb
<h1>New File</h1>

<%= render 'form' %>

<%= link_to 'Back', gfiles_path %>

app/views/gfiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @gfile.infohash.code %>
  
</p>
<p>
  <b>Permalink:</b> <%= instanceName+"/f/"+@gfile.infohash.code %>
</p>

<p>
  <b>Import link:</b> <%= link_to "/imports/doimport/"+instanceName+"/api/v1/gfiles/" + @gfile.id.to_s, "/imports/doimport/"+instanceName+"/api/v1/gfiles/" + @gfile.id.to_s %>
</p>

<p>
  <strong>Import path:</strong>
  <%= "/api/v1/gfiles/" + @gfile.id.to_s + ".json"%>
</p>

<p>
  <strong>Name:</strong>
  <%= @gfile.gtitle %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gfile.gdescription %>
</p>

<p>
  <strong>File:</strong>
  <%= link_to "Download", @gfile.filename.url %>
  <%#= @gfile.filename.url %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @gfile.infohash.user.username %>
</p>

<p>
  <strong>Members:</strong>
  <% @gfile.infohash.members.each do |u| %>
    <%= u.username %><br>
  <% end %>
</p>

<%= link_to 'Edit', edit_gfile_path(@gfile) %> |
<%= link_to 'Back', gfiles_path %>