config/routes.rb
Rails.application.routes.draw do

  resources :imports
  get '/imports/doimport/*ipath' => 'imports#doimport', as: 'ipath'
  
  resources :infohash_members
  root to: "mainpage#index"
  
  scope format: true, defaults: { format: 'html' } do
     devise_for :users, controllers: {registrations: "registrations", passwords: "passwords"}
  end
  
  namespace :api do
    namespace :v1 do
      resources :publications
      resources :gfiles
    end
  end

  resources :infohash_members
  resources :identifications  
  
  resources :supervisions
  
  resources :evaluations do
      resources :qualis_evaluate_journasl
  end
  resources :weblinks
  resources :grants

  resources :institutions

  
  get '/u/:username' => 'profiles#username', as: 'username' #creates username_path
  
  resources :profiles do
    resources :positions do
      resources :activities
    end
  end
  
  get '/g/:groupname' => 'groups#groupname', as: 'groupname' #creates groupname_path
    
  resources :groups do
      resources :group_users
  end
  
  get '/h/:code' => 'infohashes#code'
  
  resources :reminders
  resources :posts
  resources :instances
  resources :tags
  resources :gfiles

  resources :folders do
      resources :folder_infohashes
  end
  
  resources :projects do
    resources :project_profiles
  end

  get '/userpublications/:uname' => 'publications#indexbyuser', as: 'uname'
  get '/grouppublications/:gname' => 'publications#indexbygroup', as: 'gname'
  get '/f/:fcode' => 'gfiles#getfile', as: 'fcode'
  
  resources :publications do
    resources :publication_profiles
  end
  
  resources :infohashes do
    resources :infohash_users
    resources :attachments
  end
  
  
  resources :visibilities

  

end

app/models/group.rb
class Group < ActiveRecord::Base
    #has_many :infohashes,   dependent: :destroy # (expects belongs_to on the other side... not this case anymore!)
    
    belongs_to :user   #group owner
    validates_presence_of :user
    
    #has_and_belongs_to_many :infohashes, dependent: :destroy #HABTM
    has_many :group_infohashes ###, dependent: :delete_all  ### NEVER DELETE INFOHASHES BECAUSE OF GROUPS...
    has_many :infohashes, through: :group_infohashes          #HMT (through) is more flexible than HABTM
    
    ##has_many :groupmembers #=> replaced by group_users
    has_many :group_users, dependent: :delete_all
    has_many :users, through: :group_users                    #HMT (through) is more flexible than HABTM
    #has_and_belongs_to_many :users, dependent: :destroy      #HABTM
    
    validates_presence_of :name
    validates_format_of   :name, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
    
    validates_presence_of :title
    validates_presence_of :description
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    #@groups = Group.all
    @groups  = Group.joins(:group_users).where("group_users.user_id = ?", current_user.id)
    @groups += Group.where("user_id = ?", current_user.id) # owner
    @groups.uniq!
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end
  
  def groupname
    @group = Group.where('lower(name) = ?', params[:groupname].downcase).first
    render :show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.user = current_user

    respond_to do |format|
      if @group.save and GroupUser.create(:user => current_user, :group => @group)
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :title, :description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Description</th>
      <th>Group Members</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.title %></td>
        <td><%= group.description %></td>
        <td>
          <%= link_to group.user.username, group.user.profile %> (owner) <br>
          <% group.group_users.each do |gu| %>
            <%= link_to gu.user.username, gu.user.profile %>
            <% if current_user == group.user%>
              <%= link_to "(delete)", [group, gu] ,method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            <br>
          <% end %>
          <% if current_user == group.user #owner %>
              <%= link_to "New member", new_group_group_user_path(group) %>
          <% end %>
        </td>
        <td>
          <div class="btn-group" role="group" aria-label="...">
            <%= link_to 'Show', group , class: 'btn btn-default' %>
            <% if current_user == group.user %>
              <%= link_to 'Edit', edit_group_path(group), class: 'btn'  %>
              <%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn'  %>
            <% end %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @group.description %>
</p>

<p>
  <strong>Members:</strong>
  <% @group.users.each do |u|%>
  <%= u.email %>
  <% end %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>