config/routes.rb
Rails.application.routes.draw do

  resources :imports
  get '/imports/doimport/*ipath' => 'imports#doimport', as: 'ipath'
  
  resources :infohash_members
  root to: "mainpage#index"
  
  scope format: true, defaults: { format: 'html' } do
     devise_for :users, controllers: {registrations: "registrations", passwords: "passwords"}
  end
  
  namespace :api do
    namespace :v1 do
      resources :publications
      resources :gfiles
    end
  end

  resources :infohash_members
  resources :identifications  
  
  resources :supervisions
  
  resources :evaluations do
      resources :qualis_evaluate_journasl
  end
  resources :weblinks
  resources :grants

  resources :institutions

  
  get '/u/:username' => 'profiles#username', as: 'username' #creates username_path
  
  resources :profiles do
    resources :positions do
      resources :activities
    end
  end
  
  get '/g/:groupname' => 'groups#groupname', as: 'groupname' #creates groupname_path
    
  resources :groups do
      resources :group_users
  end
  
  get '/h/:code' => 'infohashes#code'
  
  resources :reminders
  resources :posts
  resources :instances
  resources :tags
  resources :gfiles

  resources :folders do
      resources :folder_infohashes
  end
  
  resources :projects do
    resources :project_profiles
  end

  get '/userpublications/:uname' => 'publications#indexbyuser', as: 'uname'
  get '/grouppublications/:gname' => 'publications#indexbygroup', as: 'gname'
  get '/f/:fcode' => 'gfiles#getfile', as: 'fcode'
  
  resources :publications do
    resources :publication_profiles
  end
  
  resources :infohashes do
    resources :infohash_users
    resources :attachments
  end
  
  
  resources :visibilities

  

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
    belongs_to :infohash #:infohash1, :class_name => 'Infohash'
    # I had to keep this as 'infohash' (not 'infohash1') because of issues with Infohash.has_many attachments
    belongs_to :infohash2, :class_name => 'Infohash'
    
    validates_presence_of :infohash
    validates_presence_of :infohash
    validates_presence_of :infohash2
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_infohash1, only: [:new, :create]
  before_action :set_attachment, only: [:destroy]

  # GET /infohashes/:infohash_id/attachments/new
  def new
    @attachment = Attachment.new
    @attachment.infohash = @infohash1
    @infohashes = Infohash.where(:user => current_user)
  end


  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment.infohash, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment.infohash }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to infohashes_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_infohash1
      @infohash1 = Infohash.find(params[:infohash_id])
    end
    
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, onl y allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:name, :infohash_id, :infohash2_id)
    end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/views/attachments/_form.html.erb
<%= form_for ([@infohash1, @attachment]) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Description" %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.hidden_field :infohash_id, :value => @infohash1.id %>
  <div class="field">
    <%= f.label "Attachment for "+@infohash1.htype.name+": "+@infohash1.gtitle %><br>
    <%#= f.text_field :infohash_id %>
    <%#= f.select :infohash2_id, options_for_select(@infohashes, 0) %>
    <% if @infohashes then %>
    <%= f.select :infohash2_id, options_for_select(@infohashes.map{|i|[i.htype.name+": "+i.gtitle, i.id]}, 0) %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', infohash_attachments_path(@infohash1) %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attachment.name %>
</p>

<p>
  <strong>Infohash:</strong>
  <%= @attachment.infohash %>
</p>

<p>
  <strong>Infohash:</strong>
  <%= @attachment.infohash %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>