config/routes.rb
Rails.application.routes.draw do

  resources :imports
  get '/imports/doimport/*ipath' => 'imports#doimport', as: 'ipath'
  
  resources :infohash_members
  root to: "mainpage#index"
  
  scope format: true, defaults: { format: 'html' } do
     devise_for :users, controllers: {registrations: "registrations", passwords: "passwords"}
  end
  
  namespace :api do
    namespace :v1 do
      resources :publications
      resources :gfiles
    end
  end

  resources :infohash_members
  resources :identifications  
  
  resources :supervisions
  
  resources :evaluations do
      resources :qualis_evaluate_journasl
  end
  resources :weblinks
  resources :grants

  resources :institutions

  
  get '/u/:username' => 'profiles#username', as: 'username' #creates username_path
  
  resources :profiles do
    resources :positions do
      resources :activities
    end
  end
  
  get '/g/:groupname' => 'groups#groupname', as: 'groupname' #creates groupname_path
    
  resources :groups do
      resources :group_users
  end
  
  get '/h/:code' => 'infohashes#code'
  
  resources :reminders
  resources :posts
  resources :instances
  resources :tags
  resources :gfiles

  resources :folders do
      resources :folder_infohashes
  end
  
  resources :projects do
    resources :project_profiles
  end

  get '/userpublications/:uname' => 'publications#indexbyuser', as: 'uname'
  get '/grouppublications/:gname' => 'publications#indexbygroup', as: 'gname'
  get '/f/:fcode' => 'gfiles#getfile', as: 'fcode'
  
  resources :publications do
    resources :publication_profiles
  end
  
  resources :infohashes do
    resources :infohash_users
    resources :attachments
  end
  
  
  resources :visibilities

  

end

app/models/identification.rb
class Identification < ActiveRecord::Base
    validates_presence_of :title
    validates_presence_of :service
    validates_presence_of :location
    
    validates_uniqueness_of :service
end

app/controllers/identifications_controller.rb
class IdentificationsController < ApplicationController
  before_action :set_identification, only: [:show, :edit, :update, :destroy]

  # GET /identifications
  # GET /identifications.json
  def index
    @identifications = Identification.all
  end

  # GET /identifications/1
  # GET /identifications/1.json
  def show
  end

  # GET /identifications/new
  def new
    @identification = Identification.new
  end

  # GET /identifications/1/edit
  def edit
  end

  # POST /identifications
  # POST /identifications.json
  def create
    @identification = Identification.new(identification_params)

    respond_to do |format|
      if @identification.save
        format.html { redirect_to @identification, notice: 'Identification was successfully created.' }
        format.json { render :show, status: :created, location: @identification }
      else
        format.html { render :new }
        format.json { render json: @identification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /identifications/1
  # PATCH/PUT /identifications/1.json
  def update
    respond_to do |format|
      if @identification.update(identification_params)
        format.html { redirect_to @identification, notice: 'Identification was successfully updated.' }
        format.json { render :show, status: :ok, location: @identification }
      else
        format.html { render :edit }
        format.json { render json: @identification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /identifications/1
  # DELETE /identifications/1.json
  def destroy
    @identification.destroy
    respond_to do |format|
      format.html { redirect_to identifications_url, notice: 'Identification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_identification
      @identification = Identification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def identification_params
      params.require(:identification).permit(:title, :service, :location)
    end
end

app/helpers/identifications_helper.rb
module IdentificationsHelper
end

app/views/identifications/_form.html.erb
<%= form_for(@identification) do |f| %>
  <% if @identification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@identification.errors.count, "error") %> prohibited this identification from being saved:</h2>

      <ul>
      <% @identification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :service %><br>
    <%= f.text_field :service %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/identifications/edit.html.erb
<h1>Editing Identification</h1>

<%= render 'form' %>

<%= link_to 'Show', @identification %> |
<%= link_to 'Back', identifications_path %>

app/views/identifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Identifications</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Service</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @identifications.each do |identification| %>
      <tr>
        <td><%= identification.title %></td>
        <td><%= identification.service %></td>
        <td><%= identification.location %></td>
        <td><%= link_to 'Show', identification %></td>
        <td><%= link_to 'Edit', edit_identification_path(identification) %></td>
        <td><%= link_to 'Destroy', identification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Identification', new_identification_path %>

app/views/identifications/new.html.erb
<h1>New Identification</h1>

<%= render 'form' %>

<%= link_to 'Back', identifications_path %>

app/views/identifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @identification.title %>
</p>

<p>
  <strong>Service:</strong>
  <%= @identification.service %>
</p>

<p>
  <strong>Location:</strong>
  <%= @identification.location %>
</p>

<%= link_to 'Edit', edit_identification_path(@identification) %> |
<%= link_to 'Back', identifications_path %>